CACHE:
    LOCATOR:
        DOCKER:
            COUNT: 2
            ENABLED: false
            HOST: 192.168.99.100
            PORT: 10334
            SPEC: 192.168.99.100:10334|localhost:10336|localhost:10338|localhost:10340|
        LOCAL:
            COUNT: 2
            HOST: localhost
            PORT: 10334
            SPEC: localhost:10334|localhost:10336|localhost:10338|localhost:10340|
