package io.kryptoblocks.msa.common.config;

// TODO: Auto-generated Javadoc
/**
 * The Class SecurityMessage.
 */
public class SecurityMessage {
	
	/** The Constant SUCCESSFUL_AUTHENTICATION_RESPONSE_MESSAGE. */
	public static final String SUCCESSFUL_AUTHENTICATION_RESPONSE_MESSAGE = "SUCCESSFUL AUTHENTICATION";
	
	/** The Constant TOKEN_NOT_CREATED_AUTHENTICATION_RESPONSE_MESSAGE. */
	public static final String TOKEN_NOT_CREATED_AUTHENTICATION_RESPONSE_MESSAGE = "UNABLE TO CREATE JWT";
	
	/** The Constant UNABLE_TO_FIND_USER_FROM_AUTH_DATA_STOR_AUTHENTICATION_RESPONSE_MESSAGE. */
	public static final String UNABLE_TO_FIND_USER_FROM_AUTH_DATA_STOR_AUTHENTICATION_RESPONSE_MESSAGE = "UNABLE TO FIND THE USER FROM AUTHORIZATION STORE USING THE AUTHENTICATION DATA";
	
	/** The Constant UNABLE_TO_AUTHENTICATE_USERNAME_PASSWORD_AUTHENTICATION_RESPONSE_MESSAGE. */
	public static final String UNABLE_TO_AUTHENTICATE_USERNAME_PASSWORD_AUTHENTICATION_RESPONSE_MESSAGE = "UNABLE TO AUTHENTICATE INPUT USER NAME AND PASSWORD";
	
	/** The Constant UNABLE_TO_AUTHENTICATE_KRB_TICKET_AUTHENTICATION_RESPONSE_MESSAGE. */
	public static final String UNABLE_TO_AUTHENTICATE_KRB_TICKET_AUTHENTICATION_RESPONSE_MESSAGE = "UNABLE TO AUTHENTICATE INPUT KRB TOKEN";
	
	/** The Constant INVALID_JWT_TOKEN_AUTHENTICATION_RESPONSE_MESSAGE. */
	public static final String INVALID_JWT_TOKEN_AUTHENTICATION_RESPONSE_MESSAGE = "EXPIRED_JWT_TOKEN";	
	
	/** The Constant AUTH_VERIFICATION_SUCCESS_RESPONSE_MESSAGE. */
	public static final String AUTH_VERIFICATION_SUCCESS_RESPONSE_MESSAGE = "AUTHORIZATION LIST IS VERIFIED";	
	
	/** The Constant AUTH_VERIFICATION_INVALID_TOKEN_SUCCESS_RESPONSE_MESSAGE. */
	public static final String AUTH_VERIFICATION_INVALID_TOKEN_SUCCESS_RESPONSE_MESSAGE = "INVALID OR EXPIRED TOKEN";
	
	


}
