INSERT INTO USER (ID, USERNAME) VALUES (1, 'ADMIN');
INSERT INTO USER (ID, USERNAME) VALUES (2, 'USER');
INSERT INTO USER (ID, USERNAME) VALUES (3, 'SERVICE');
INSERT INTO USER (ID, USERNAME) VALUES (4, 'AT1016401');

INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'SERVICE_OP_RD');
INSERT INTO AUTHORITY (ID, NAME) VALUES (2, 'SERVICE_OP_WT');
INSERT INTO AUTHORITY (ID, NAME) VALUES (3, 'SERVICE_OP_DL');
INSERT INTO AUTHORITY (ID, NAME) VALUES (4, 'SERVICE_OP_UT');
INSERT INTO AUTHORITY (ID, NAME) VALUES (5, 'SERVICE_AD');


INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (3, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (4, 3);
